# CoinDCX API settings
api:
  public_base_url: "https://public.coindcx.com"  # For public endpoints like /market_data
  api_base_url: "https://api.coindcx.com"        # For authenticated endpoints like /exchange
  api_key: "376a11ea349817010f8283e382b7ddc879c12c637a6c714b"
  api_secret: "bda2091e1095547751a75ea180db885a9a026bcdee85fba88ada7c9cbbb03711"

# External Data API settings
external_apis:
  cryptocompare:
    enabled: true
    api_key: "305278f1f0feb851ccb23cbab26a6d5078703085633826503c363b4084e53e5d"
    base_url: "https://min-api.cryptocompare.com"
    max_retries: 3
    timeout: 10

# Trading settings
trading:
  initial_balance: 10000  # INR
  position_size_ratio: 0.25  # 25% of balance per trade (increased from 10%)
  instruments:
    - B-BTC_USDT
    - B-ETH_USDT
    - B-XRP_USDT
    - B-ADA_USDT
    - B-DOT_USDT
    - B-SOL_USDT
    - B-BNB_USDT
    - B-MATIC_USDT
    - B-LINK_USDT
    - B-TRX_USDT
    - B-AVAX_USDT
  timeframes:
    scalping: ["1m", "5m"]  # 1m and 5m for true scalping opportunities
    swing: ["15m","1h"]  # Focus on 15m and 1h for swing
    long_swing: []  # Disabled long swing
    trend: ["1d"]  # Keep 1d for trend
  scalping:
    relaxed: true             # Relax filters to allow more scalp signals
    max_spread_pct: 0.35      # Keep tight spread for quality
    max_slippage_pct: 0.30    # Tighter slippage for scalping validation
    min_volume_ratio: 0.7     # Require >=70% of 20-SMA volume for entries
    # Note: Per-candle volumes are in base units; use realistic thresholds for 1m/5m
    min_avg_volume: 800       # Average volume over last 20 candles (base units)
    min_current_volume: 500   # Current candle volume (base units)
    min_volatility_pct: 0.3   # Allow lower ATR% on 1m/5m
    max_volatility_pct: 12.0  # Allow higher ATR% environments
    min_volume_surge: 1.1     # 1.1x average volume
    min_conditions_score: 6   # Fewer conditions needed
  leverage:
    scalping: 25
    swing: 25
    long_swing: 25
    trend: 25
  risk_reward:
    scalping: 2
    swing: 2
    long_swing: 2.5
    trend: 3
  min_profit_inr: 100
  fees:
    taker: 0.00075  # 0.075%
    maker: 0.00025  # 0.025%

  # Signal generation and monitoring settings - OPTIMIZED FOR PERFORMANCE
  signal_generation:
    max_signals: 20  # Reduced from 40 for faster generation
    max_monitor_signals: 15  # Monitor top 15 signals
    min_score_threshold: 5  # Score threshold for quality
    max_active_signals: 15  # Monitor top 15 active signals
    max_active_trades: 15  # Maximum active trades
    profit_threshold: 300  # Minimum estimated profit
    confidence_threshold: 0.5  # Confidence threshold
    min_profit_for_monitoring: 200  # Minimum profit for monitoring
    # Top movers and ATR filter tuning to increase candidates
    top_movers_count: 50
    min_volume_for_top_movers: 200000
    min_volume_for_atr_filter: 200000
    min_atr_pct_filter: 0.6
    top_filtered_count: 20
    # Increase scalping share
    strategy_order: ["scalping", "swing"]
    max_scalping_signals: 10
    max_swing_signals: 6
    max_long_swing_signals: 0
    max_final_signals: 20
    # Generate signals only during allowed IST hours to avoid weak afternoon sessions
    # Ranges are inclusive; example below allows 18:00–23:59 and 00:00–02:59 IST
    allowed_ist_hours:
      - [18, 23]
      - [0, 2]
    disable_time_filter: true  # set true to allow generation at any time (for testing)
    # Ensure a minimum number of SHORT signals are selected when available
    min_short_signals: 5

# Logging settings
logging:
  log_file: "logs/trading_bot.log"
  level: "INFO"