# CoinDCX API settings
api:
  public_base_url: "https://public.coindcx.com"  # For public endpoints like /market_data
  api_base_url: "https://api.coindcx.com"        # For authenticated endpoints like /exchange
  api_key: ""
  api_secret: "bda2091e1095547751a75ea180db885a9a026bcdee85fba88ada7c9cbbb03711"

# External Data API settings
external_apis:
  cryptocompare:
    enabled: true
    api_key: "305278f1f0feb851ccb23cbab26a6d5078703085633826503c363b4084e53e5d"
    base_url: "https://min-api.cryptocompare.com"
    max_retries: 3
    timeout: 10

# Trading settings
trading:
  initial_balance: 10000  # INR
  position_size_ratio: 0.25  # 25% of balance per trade (increased from 10%)
  instruments:
    - B-BTC_USDT
    - B-ETH_USDT
    - B-XRP_USDT
    - B-ADA_USDT
    - B-DOT_USDT
    - B-SOL_USDT
    - B-BNB_USDT
    - B-MATIC_USDT
    - B-LINK_USDT
    - B-TRX_USDT
    - B-AVAX_USDT
  timeframes:
    scalping: ["1m", "5m"]  # 1m and 5m for true scalping opportunities
    swing: ["15m","1h"]  # Focus on 15m and 1h for swing
    long_swing: ["1h"]  # Reduced to only 1h for long swing (remove 30m)
    trend: ["1d"]  # Keep 1d for trend
  scalping:
    relaxed: true             # Enable relaxed filters to ensure some scalp signals
    max_spread_pct: 1.0       # Allow up to 1.0% spread
    min_avg_volume: 50000     # Relaxed volume thresholds
    min_current_volume: 30000
    min_volatility_pct: 0.5   # Allow lower ATR% environments
    max_volatility_pct: 12.0  # Allow higher ATR% environments
    min_volume_surge: 1.2     # 1.2x average volume
    min_conditions_score: 6   # Fewer conditions needed
  leverage:
    scalping: 25
    swing: 25
    long_swing: 25
    trend: 25
  risk_reward:
    scalping: 2
    swing: 2
    long_swing: 2.5
    trend: 3
  min_profit_inr: 100
  fees:
    taker: 0.00075  # 0.075%
    maker: 0.00025  # 0.025%

  # Signal generation and monitoring settings - OPTIMIZED FOR PERFORMANCE
  signal_generation:
    max_signals: 20  # Reduced from 40 for faster generation
    max_monitor_signals: 15  # Monitor top 15 signals
    min_score_threshold: 5  # Score threshold for quality
    max_active_signals: 15  # Monitor top 15 active signals
    max_active_trades: 15  # Maximum active trades
    profit_threshold: 300  # Minimum estimated profit
    confidence_threshold: 0.5  # Confidence threshold
    min_profit_for_monitoring: 200  # Minimum profit for monitoring
    # Top movers and ATR filter tuning to increase candidates
    top_movers_count: 50
    min_volume_for_top_movers: 200000
    min_volume_for_atr_filter: 200000
    min_atr_pct_filter: 0.6
    top_filtered_count: 20
    # Increase scalping share
    strategy_order: ["scalping", "swing", "long_swing"]
    max_scalping_signals: 10
    max_swing_signals: 6
    max_long_swing_signals: 1
    max_final_signals: 20

# Logging settings
logging:
  log_file: "logs/trading_bot.log"
  level: "INFO"